-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
--
--
--Uncomment to show invisible characters (tabs and spaces)
-- vim.opt.list = true
-- vim.opt.listchars:append({ tab = ">-", space = "." })
